### ISSUE TITLE
Quickstart problem

### ISSUE THREAD

**Issue by michaelGregoire** [asgardphp/docs#1]
Not sure if there's a problem or it's something I'm missing, but when I try to install the news module with the command line found in the quickstart:

php console install https://github.com/asgardmodules/news.git=v0.2.0 --update-composer --migrate

I receive the following error:

error: pathspec 'tags/v0.2.0' did not match any file(s) known to git.
The files could not be downloaded.

It looks like it's trying to checkout "tags/v0.2.0". Shouldn't it be trying to checkout "v0.2.0"?

This is the command output prior to the error:
cd "/Path/To/asgard/tmp/UBVMYwtrTS" & git checkout tags/v0.2.0

**Comment by h0gar** [comment]
Hi Michael,
I was actually working on the new 0.2.0 tag this morning so you probably did the quickstart right when things were being updated.

To be sure, can you please create a new empty folder and run these commands:
git clone --recursive https://github.com/asgardmodules/news.git .
git checkout tags/v0.2.0

If this work the quickstart should work. Again, I have updated the docs and the files this morning so you should retry the quickstart from scratch. Sorry about that!

**Comment by michaelGregoire** [comment]
Thanks for the quick response. That worked in the empty directory.

**Comment by michaelGregoire** [comment]
Though the quickstart still fails. Here's all the output from the news module command:

git clone --recursive "https://github.com/asgardmodules/news.git" "/Path/To/asgard/tmp/7EpQkVaStt"
Cloning into '/Path/To/asgard/tmp/7EpQkVaStt'...
remote: Counting objects: 371, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 371 (delta 0), reused 0 (delta 0), pack-reused 368
Receiving objects: 100% (371/371), 409.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (154/154), done.
Checking connectivity... done.
cd "/Path/To/asgard/tmp/7EpQkVaStt" & git checkout tags/v0.2.0
error: pathspec 'tags/v0.2.0' did not match any file(s) known to git.
The files could not be downloaded.
composer update --working-dir "/Path/To/asgard"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

**Comment by michaelGregoire** [comment]
Interesting... if I manually cd into the temporary directory and then try to checkout tags/v0.2.0, that works. But not in the context of the news module install command.

**Comment by michaelGregoire** [comment]
There's something about this command that git doesn't like:

cd "/Path/To/asgard/tmp/zauH4WxYgl" & git checkout tags/v0.2.0

When you do the two commands separately:

cd "/Path/To/asgard/tmp/zauH4WxYgl"
git checkout tags/v0.2.0

....it works.

**Comment by h0gar** [comment]
Oh, weird. Thanks for the details, I will fix that a bit later today.

Btw which system are you using?

**Comment by michaelGregoire** [comment]
Thanks. OSX 10.8.5

**Comment by h0gar** [comment]
Hi,
I have fixed this specific issue, however there are a few more things I want to check. I'll let you know when I'm done.

**Comment by michaelGregoire** [comment]
Ok, thanks for the update.

**Comment by h0gar** [comment]
All good. You can do the quickstart. Probably better though if you restart from scratch.

**Comment by michaelGregoire** [comment]
Sounds good. Thanks @h0gar.

**Comment by michaelGregoire** [comment]
Worked like a charm. Thanks for your help.

**Comment by h0gar** [comment]
Hi ,
Did you go through the whole tutorial?
If so, how long did it take and did it all make sense to you? I'd like to hear your comments if you have any :)

**Comment by michaelGregoire** [comment]
Thanks for checking. Unfortunately, there's a bug in the News module. When I try to add a news post in the admin section, it fails with:

**Error**
**Oops, something went wrong.**

Nothing more than that. This brings up an important point... does Asgard output debug info to a log? Perhaps by default, some sort of debugging information should be included on the error view.

**Comment by h0gar** [comment]
It does output debug info, but only in the "dev" environment. It detects this environment if php is executed through cli or if the host is equal to 127.0.0.1 or localhost. Otherwise you can switch the default environment with the command: php console env:switch dev, or by adding this line at the beginning of the web/index.php file: define('_ENV_', 'dev');
I wonder though why it doesn't default to dev in your case. What does "$_SERVER['HTTP_HOST']" return for you?

Once you get the debug info, can you copy/paste the top part here?
